import ReduxProvider from "@/redux/ReduxProvider";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Open_Sans } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Favicon from "@/assets/icons/Favicon (2).png";
import { i18n } from '@/lib/i18n/i18n-config';
import { ReactNode } from "react";

const openSans = Open_Sans({
  subsets: ["latin"],
  style: ["normal", "italic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Jags",
  description: "Generated by Jags",
  icons: {
    icon: Favicon.src,
  },
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}


export interface LayoutProps {
  children: ReactNode;
  params?: Promise<{ lang?: string }>;
}

export default async function RootLayout({ children, params }: LayoutProps) {
  const resolvedParams = await params;
  const lang = resolvedParams?.lang || "en";
  return (
    <html lang={lang}>
      <body className={openSans.className}>
        <ReduxProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster position="top-right" richColors />
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
